name: Thearetical
favicon: null
layout_spectrum: 0.9039083539973944
typography_spectrum: 0.3639152452815324
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.4893694301135838
  lightness: 0.3442917943466455
  saturation: 0.576198254013434
  rhythmicContrast: 0.7487391645554453
purpose: []
